import { BasketIcon } from "@sanity/icons"
import { defineArrayMember, defineField, defineType } from "sanity"
import { ORDER_STATUS_SANITY_LIST } from "@/lib/constants/orderStatus"

/**
 * Order Document Schema
 *
 * Represents a customer order in the e-commerce system. Orders are created automatically
 * via Stripe webhooks when a payment is successful. Contains order items, customer info,
 * and payment details.
 *
 * @field orderNumber - Unique order identifier (required, read-only, auto-generated)
 * @field items - Array of ordered products with quantity and purchase price
 * @field total - Total order amount in GBP (read-only, calculated)
 * @field status - Order status (paid, processing, shipped, delivered, cancelled)
 * @field customer - Reference to customer document
 * @field clerkUserId - Clerk authentication ID (read-only)
 * @field email - Customer email (read-only)
 * @field address - Shipping address object
 * @field stripePaymentId - Stripe payment intent ID (read-only)
 * @field createdAt - Order creation timestamp (read-only, auto-generated)
 *
 * @group details - Order items, total, status, and date
 * @group customer - Customer reference, user ID, email, and shipping address
 * @group payment - Stripe payment information
 *
 * @preview Shows order number, customer email, total amount, and status
 * @orderings Can be sorted by creation date (newest first)
 *
 * @note Orders are created by Stripe webhooks and should not be manually created
 * @note Stock levels are automatically decremented when orders are created
 */
export const orderType = defineType({
  name: "order",
  title: "Order",
  type: "document",
  icon: BasketIcon,
  groups: [
    { name: "details", title: "Order Details", default: true },
    { name: "customer", title: "Customer" },
    { name: "payment", title: "Payment" }
  ],
  fields: [
    defineField({
      name: "orderNumber",
      title: "Order Number",
      type: "string",
      group: "details",
      readOnly: true,
      description:
        "Unique order identifier. Auto-generated by the system when order is created via webhook.",
      validation: (rule) => [rule.required().error("Order number is required")]
    }),
    defineField({
      name: "items",
      title: "Order Items",
      type: "array",
      group: "details",
      description:
        "Products included in this order with quantities and prices at time of purchase.",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "product",
              title: "Product",
              type: "reference",
              to: [{ type: "product" }],
              description: "Reference to the ordered product.",
              validation: (rule) => rule.required()
            }),
            defineField({
              name: "quantity",
              title: "Quantity",
              type: "number",
              initialValue: 1,
              description: "Number of units ordered.",
              validation: (rule) => rule.required().min(1)
            }),
            defineField({
              name: "priceAtPurchase",
              title: "Price at Purchase",
              type: "number",
              description:
                "Price per unit at the time of purchase (in GBP). Preserved for historical accuracy even if product price changes.",
              validation: (rule) => rule.required()
            })
          ],
          preview: {
            select: {
              title: "product.name",
              quantity: "quantity",
              price: "priceAtPurchase",
              media: "product.images.0"
            },
            prepare({ title, quantity, price, media }) {
              return {
                title: title ?? "Product",
                subtitle: `Qty: ${quantity} • £${price}`,
                media
              }
            }
          }
        })
      ]
    }),
    defineField({
      name: "total",
      title: "Order Total",
      type: "number",
      group: "details",
      readOnly: true,
      description:
        "Total order amount in GBP. Calculated from sum of (quantity × priceAtPurchase) for all items."
    }),
    defineField({
      name: "status",
      title: "Order Status",
      type: "string",
      group: "details",
      initialValue: "paid",
      description:
        "Current status of the order. Update this to track order fulfillment progress.",
      options: {
        list: ORDER_STATUS_SANITY_LIST,
        layout: "radio"
      }
    }),
    defineField({
      name: "customer",
      title: "Customer",
      type: "reference",
      to: [{ type: "customer" }],
      group: "customer",
      description: "Reference to the customer who placed this order."
    }),
    defineField({
      name: "clerkUserId",
      title: "Clerk User ID",
      type: "string",
      group: "customer",
      readOnly: true,
      description:
        "Clerk authentication user ID. Links order to authenticated user account."
    }),
    defineField({
      name: "email",
      title: "Customer Email",
      type: "string",
      group: "customer",
      readOnly: true,
      description:
        "Customer's email address at time of order. Used for order confirmation and updates."
    }),
    defineField({
      name: "address",
      title: "Shipping Address",
      type: "object",
      group: "customer",
      description:
        "Delivery address for this order. Captured from Stripe checkout.",
      fields: [
        defineField({
          name: "name",
          type: "string",
          title: "Full Name",
          description: "Recipient's full name"
        }),
        defineField({
          name: "line1",
          type: "string",
          title: "Address Line 1",
          description: "Street address, P.O. box, company name"
        }),
        defineField({
          name: "line2",
          type: "string",
          title: "Address Line 2",
          description: "Apartment, suite, unit, building, floor, etc."
        }),
        defineField({ name: "city", type: "string", title: "City" }),
        defineField({ name: "postcode", type: "string", title: "Postcode" }),
        defineField({ name: "country", type: "string", title: "Country" })
      ]
    }),
    defineField({
      name: "stripePaymentId",
      title: "Stripe Payment ID",
      type: "string",
      group: "payment",
      readOnly: true,
      description:
        "Stripe Payment Intent ID. Use this to look up payment details in Stripe Dashboard."
    }),
    defineField({
      name: "createdAt",
      title: "Created At",
      type: "datetime",
      group: "details",
      readOnly: true,
      description:
        "Timestamp when the order was created. Auto-generated by the system.",
      initialValue: () => new Date().toISOString()
    })
  ],
  preview: {
    select: {
      orderNumber: "orderNumber",
      email: "email",
      total: "total",
      status: "status"
    },
    prepare({ orderNumber, email, total, status }) {
      return {
        title: `Order ${orderNumber ?? "N/A"}`,
        subtitle: `${email ?? "No email"} • £${total ?? 0} • ${status ?? "paid"}`
      }
    }
  },
  orderings: [
    {
      title: "Newest First",
      name: "createdAtDesc",
      by: [{ field: "createdAt", direction: "desc" }]
    }
  ]
})
